### ISSUE TITLE
Organization list of contacts is not formatted anymore

### ISSUE THREAD

**Issue by ghost** [certat/customer-portal#1]
On the contact list page (`#!/user_list`) the list of organization is now unformatted. It should be a comma separated list.

currently:
![do-portal-screenshot_2018-09-05_15-08-44](https://user-images.githubusercontent.com/25031221/45095201-c6aa0800-b11d-11e8-943c-2699c9bf418d.png)
desired state (production):
![do-portal-screenshot_2018-09-05_15-10-48](https://user-images.githubusercontent.com/25031221/45095242-e5a89a00-b11d-11e8-9641-2427c050d1bf.png)

**Comment by davewood** [comment]
fixed:

0a4f56b526f10048d3afeaf0f3e675f0358bbddf 
cbb8bc50521209a7b8027988143d27021293018c

**Comment by ghost** [comment]
confirmed
