### ISSUE TITLE
default page is login even if already logged in

### ISSUE THREAD

**Issue by ghost** [certat/customer-portal#2]
1. User is logged in
2. User opens `/`
3. the login page `#!/login` is shown even if other pages `#!/organization_list` do work.

The logged-in user should not see the login page but instead `#!/organization_list` (the page after the login)

**Comment by davewood** [comment]
fixed

* fe0b3f6 - (HEAD -> release, origin/release, topic_multiorga) dont show login mask if user is logged in (3 minutes ago) <David Schmidt>
