### ISSUE TITLE
OrgAdmins can set parent organisation for sub-organisations

### ISSUE THREAD

**Issue by ghost** [certat/customer-portal#9]
E.g. The following org hierarchy:

 - Org 29
   - Org 35
     - Org 36

OrgAdmin of Org 29 should be able set the parent Org of Org 36 to any org he can see (i.e. 29, 35).

**Comment by certrik** [comment]
To clarify ... this is only possible at the creation time of the organization at the moment. But this should also be possible after the initial creation in the "edit" menu of the organization.
